# Generated by Django 5.0 on 2023-12-10 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="horario",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
